FROM node:20-alpine AS base

RUN npm install -g pnpm

WORKDIR /usr/src/app

COPY ./package.json ./package.json
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY ./turbo.json ./turbo.json
COPY ./packages ./packages
COPY ./apps/drawnew ./apps/drawnew

RUN pnpm install

RUN pnpm run db:generate

WORKDIR /usr/src/app

RUN pnpm run build

EXPOSE 3000

CMD ["pnpm", "run", "start:drawnew"]
