FROM node:20-alpine AS base

RUN npm install -g pnpm

WORKDIR /usr/src/app


COPY ./packages ./packages
COPY ./package.json ./package.json
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY ./turbo.json ./turbo.json
COPY ./apps/drawnew ./apps/drawnew

RUN npm install prisma@6.5.0

RUN pnpm install
RUN pnpm run db:generate
RUN pnpm run build


EXPOSE 3000

CMD ["sh", "-c", "pnpm run db:generate && pnpm run start:drawnew"]
